In [53]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [106]:
import numpy as np

In [57]:
# NumPy example
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [59]:
#With Numpy
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = a * b
print(c)

#Without Numpy
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
c = []
for i in range(len(a)):
    c.append(a[i] * b[i])
print(c)

[ 5 12 21 32]
[5, 12, 21, 32]


In [61]:
a = np.array([1, 2, 3, 4])
print("Array 1D",a)

b = np.array([[1, 2],[ 3, 4]])
print("Array 2D\n",b)

Array 1D [1 2 3 4]
Array 2D
 [[1 2]
 [3 4]]


In [94]:
o= np.ones((3,6))
print("ones \n", o)

z= np.zeros((10,10)) 
print("zeros \n", z)

i = np.eye(8)
print("Identical coordinates: \n", i)

r = np.arange(0,11,2) 
print("Array: ", r)

seperate= np.linspace (0,1, 5)#creates 5 evenly spaced numbers between 0 and 1 (inclusive).
print("linspace", seperate)

ones 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
zeros 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Identical coordinates: 
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
Array:  [ 0  2  4  6  8 10]
linspace [0.   0.25 0.5  0.75 1.  ]


In [102]:
'''operationms on array using Numpy'''
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
print("Addition : ", a1 + a2)#The Two lists must in same Size
print("Product : ", a1 * a2)
print("Square : ", a1**2)
print("Sin Values : " ,np.sin(a1))
print("Mean : ",np.mean(a1))
print("Max : ",np.max(a1))

Addition :  [ 6  8 10 12]
Product :  [ 5 12 21 32]
Square :  [ 1  4  9 16]
Sin Values :  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Mean :  2.5
Max :  4


In [136]:
a=np.arange(1,10)
print(a)

reshaped = a.reshape(3,3)
print(reshaped)

linear=reshaped.reshape(-1) 
print(linear)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [177]:
a= np.arange(1,10)
print(a)

reshaped= a.reshape((3,3))
print (reshaped)

print("Element at (1,1):", reshaped [1,1])
linear= reshaped.flatten()
print(linear)

print("greater than 5:", linear [linear>5])
print("Lesser than 5:", linear [linear<5])

print("Random numbers between 0 to 1:", np.random.rand()) 
print("Random numbers between 0 to 1:", np.random.rand(3)) 

print("Random integer between 1 and 100:", np.random.randint(1, 100) )# single random int
print("Random integer :", np.random.randint(1, 100,size=3) )
print("Random 2x3 array of integers between 1 and 100:\n", np.random.randint(1, 100, size=(2, 3)))


a=np.random.randint(1, 100, size=5) 
print(a)# 5 random integers


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,1): 5
[1 2 3 4 5 6 7 8 9]
greater than 5: [6 7 8 9]
Lesser than 5: [1 2 3 4]
Random numbers between 0 to 1: 0.13140539758088354
Random numbers between 0 to 1: [0.11510451 0.28020108 0.9025794 ]
Random integer between 1 and 100: 78
Random integer : [42 66 37]
Random 2x3 array of integers between 1 and 100:
 [[16  1 65]
 [63 63 53]]
[88 97 12 17  8]


In [201]:
'''code to print a 3X3 matrix which were filled with boolean value True using numpy'''
matrix = np.ones((3, 3), dtype=bool)
print(matrix)

print()

matrix = np.zeros((3, 3), dtype=bool)
print(matrix)


print()
#2
matrix = np.full((3, 3), True)
print(matrix)

#3
print()
matrix = np.full((3, 3), True,dtype=bool)
print(matrix)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
