In [28]:
'''vertical and horizontal - vstack and hstack
code to take two arrays a and b integrate a and b vertically and horizontzlly'''

import numpy as np

a = list(map(int, input("Enter 3 numbers for array a, space separated: ").split()))
b = list(map(int, input("Enter 3 numbers for array b, space separated: ").split()))

a = np.array(a)
b = np.array(b)
print("Vertical Stack:\n", np.vstack((a, b))) #also using [a,b] in hstack,vstack
print("Horizontal Stack:\n", np.hstack((a, b)))

v=np.vstack((a,b))
print("Elements 5 access ",v[1,1])
print("Elements 5 access ",v[1][1])

Enter 3 numbers for array a, space separated:  1 2 3 
Enter 3 numbers for array b, space separated:  4 5 6


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Elements 5 access  5
Elements 5 access  5


In [10]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.hstack((a, b))
print(res)

[1 2 3 4 5 6]


In [12]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

res = np.hstack((a, b))
print(res)

[[1 2 5 6]
 [3 4 7 8]]


In [68]:
import numpy as np

# Create sample arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([[7, 8], [9, 10]])
array4 = np.array([[11, 12], [13, 14]])

# Horizontal stacking
h_stacked = np.hstack((array1, array2))
print("Horizontal Stack (1D arrays):\n", h_stacked)

h_stacked_2d = np.hstack((array3, array4))
print("\nHorizontal Stack (2D arrays):\n", h_stacked_2d)

# Vertical stacking
v_stacked = np.vstack((array1, array2))
print("\nVertical Stack (1D arrays):\n", v_stacked)

v_stacked_2d = np.vstack((array3, array4))
print("\nVertical Stack (2D arrays):\n", v_stacked_2d)

Horizontal Stack (1D arrays):
 [1 2 3 4 5 6]

Horizontal Stack (2D arrays):
 [[ 7  8 11 12]
 [ 9 10 13 14]]

Vertical Stack (1D arrays):
 [[1 2 3]
 [4 5 6]]

Vertical Stack (2D arrays):
 [[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [40]:
'''code to extract all the odd numbers from user input and print them in a list using array of numpy
input: 1 2 3 4 5 9 8 7 6
output: 1,3,5,9,7'''
import numpy as n
data=input("Enter Numbers separated by spaces : ")
arr=np.array(list(map(int,data.split())))
odd=arr[arr%2==1]
print("Odd Numbers List : ",odd)


Enter Numbers separated by spaces :  1 2 3 4 5 6 7 8 9


Odd Numbers List :  [1 3 5 7 9]


In [44]:
# Now Replace odd places with -1
import numpy as np
# Input numbers
numbers = list(map(int, input("Enter numbers separated by space: ").split()))
# Convert to numpy array
arr = np.array(numbers)
# Replace odd numbers with -1
arr[arr % 2 != 0] = -1
'''arr = np.where(arr % 2 != 0, -1, arr)'''
# Print the modified array
print("Modified array:", arr)
print("Modified array:", arr.tolist())

Enter numbers separated by space:  1 2 3 4 5 6 7 8 9


Modified array: [-1  2 -1  4 -1  6 -1  8 -1]
Modified array: [-1, 2, -1, 4, -1, 6, -1, 8, -1]


In [54]:
#Replace True or False 
import numpy as n
data=input("Enter Numbers separated by spaces : ")
arr=np.array(list(map(int,data.split())),dtype=object)
arr[arr%2==1]=True
arr[arr%2==0]=False
print(" List : ",arr)

Enter Numbers separated by spaces :  1 2 3 4 5 6 7 8 9


 List :  [True False True False True False True False True]


In [66]:
#Multiple with 3 is True remaining is  False

import numpy as np
data = input("Enter Numbers separated by spaces: ")
arr = np.array(list(map(int, data.split())),dtype=object)
# Mark multiples of 3 as True, others as False
arr = arr % 3 == 0
print("List:", arr)


mask=arr % 3 == 0
print(mask)

# Set multiples of 3 to True
arr[arr % 3 == 0] = True
# Set all other elements to False
arr[arr != True] = False  # everything not True becomes False
print("List:", arr)


Enter Numbers separated by spaces:  1 2 3 4 5


List: [False False  True False False]
[ True  True False  True  True]
List: [ True  True  True  True  True]


In [30]:
'''code to extract all the odd numbers from user input and print them in a list using array of numpy
input: 1 2 3 4 5 9 8 7 6
output: 1,3,5,9,7'''

import numpy as np
# Take space-separated numbers as input
numbers = list(map(int, input("Enter numbers separated by space: ").split()))
# Convert to NumPy array
arr = np.array(numbers)
# Use boolean indexing to filter odd numbers
odd_numbers = arr[arr % 2 != 0]
'''# Find indices where elements are odd
odd_indices = np.where(arr % 2 != 0)
# Extract odd numbers using the indices
odd_numbers = arr[odd_indices]'''
# Print the result as a comma-separated list
print("Odd numbers:", ','.join(map(str, odd_numbers)))


Enter numbers separated by space:  1 2 3 4 5 6 7 8 9


Odd numbers: 1,3,5,7,9


In [70]:
import numpy as np
a = np.array([1, 2, 3])
b = a * 2  # multiplies each element by 2
print(b)  # Output: [2 4 6]


[2 4 6]


In [102]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6]])
print("Element at [0,1]:",arr[0,1])
print("First row:", arr[0,:])
print("Second row:", arr[1,:])
print("\nFirst Row : \n",arr[:,1:])

print("\nAnd Total rows:\n", arr[0:])
print("And Total rows:\n", arr[1:])

arr[0,0]=100
print("\nModify : \n",arr)



Element at [0,1]: 2
First row: [1 2 3]
Second row: [4 5 6]

First Row : 
 [[2 3]
 [5 6]]

And Total rows:
 [[1 2 3]
 [4 5 6]]
And Total rows:
 [[4 5 6]]

Modify : 
 [[100   2   3]
 [  4   5   6]]


In [131]:
import numpy as np
arr= np.array([1,2,3, np.nan, 5])
print("Mean Ignoring NaN : ",np.nanmean(arr))
print("Mean Ignoring NaN : ",np.nansum(arr))
print("Sum : ",np.sum(arr))
#Sqrt1.N Ei = 1 to N(x~1=u)**2
print("std Ignoring NaN:", np.std(arr[~np.isnan (arr)]))
arr= np.array([1,2,3, 5])
print("Sum: " , np.sum(arr))
print("Std " , np.std(arr))

Mean Ignoring NaN :  2.75
Mean Ignoring NaN :  11.0
Sum :  nan
std Ignoring NaN: 1.479019945774904
Sum:  11
Std  1.479019945774904


In [133]:
#replace NaN
import numpy as np
arr= np.array([1, np. nan, 3, 4, 5])
print("replace NaN with 0:", np.where(np.isnan(arr), 0, arr))

replace NaN with 0: [1. 0. 3. 4. 5.]


In [159]:
import numpy as np

arr = np.array([1.5, 2, 9, 9, 8])
print(arr.astype(np.int32))  # Convert float to int (truncates decimals)

arr = np.array([1, 2, 3, 4])
print(arr.astype(np.float64))  # Convert int to float

arr = np.array([1.5, 2.9, 9.8])
print(arr.astype(str))  # Convert numbers to strings


arr = np.array(["1", "2", "3", "4.5"])

arr_float = arr.astype(float)  # Convert all strings to float first
arr_int = arr_float.astype(int)  # Then convert floats to int (drops decimals)

print(arr_int)
int(arr.astype(int))  # Converts strings are integers

arr = np.array([0, 1, 7, 0])
print(arr.astype(bool))  # Convert numbers to boolean (0 -> False, nonzero -> True)

arr = np.array([True, True, False, True])
print(arr.astype(np.int32))

arr= np.array ([1.5, 2.9, 9.8])
print(arr.astype(np.complex128))

arr = np.array([1, 2, 3, 4])
print(arr.astype(np.int8))

arr = np.array([20250802, 19991224])
print(arr.astype('datetime64[D]'))

[1 2 9 9 8]
[1. 2. 3. 4.]
['1.5' '2.9' '9.8']


ValueError: invalid literal for int() with base 10: '4.5'